language: java
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 67fba3ed-a973-4576-b433-05636389c139
notifications:
  email:
    recipients:
      - daniel.fuevesi@gmail.com
    on_failure: always
