version: '3.1'

services:
  backend:
    build: ./backend
    image: waecm_backend:waecm-2018-group-09-bsp-1
    restart: always
    container_name: backend
    ports:
      - 8182:8080
    depends_on:
      - mongo

  mongo:
    build: ./database
    image:  waecm_mongo:waecm-2018-group-09-bsp-1
    container_name: waecm-mongo-db
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/db:/data/db
      - $HOME/data/bkp:/data/bkp
    restart: always

  swagger:
    environment:
      - API_URL=http://localhost:8182/swagger
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8888:8080
    depends_on:
      - mongo
      - backend
    restart: always
