version: '3.1'

services:
  backend:
    build: ./backend
    image: rasakul/waecm-2018-group-09-bsp-1-backend
    restart: always
    container_name: waecm-backend
    ports:
      - 8182:8080
    depends_on:
      - mongo

  mongo:
    build: ./database
    image:  rasakul/waecm-2018-group-09-bsp-1-mongo
    container_name: waecm-mongo-db
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/db:/data/db
      - $HOME/data/bkp:/data/bkp
    restart: always

  frontend:
    build: ./frontend
    image:  rasakul/waecm-2018-group-09-bsp-1-frontend
    restart: always
    container_name: waecm-frontend
    ports:
      - 5000:5000
    depends_on:
      - backend
