spring:
  security:
    user:
      name: user
      password: EprL4Meb8nitcQwf
  application:
    name: Web Application Engineering Backend
  data:
    mongodb:
      port: 27017
      database: waecmDatabase
      host: localhost
      username: user
      password: devPassword
  profiles:
    active: dev